### ISSUE TITLE
why do you use RabbitMQ

### ISSUE THREAD

**Issue by HoangNgo88** [BetterCorp/service-base-events-rabbitmq#3]
Hi, I am reading your project and I love this project
I have a question, why do you choose RabbitMQ in your project instead of others like ZeroMQ or Kafka, are there any special features but others dont have it. Can you share me  it. I am wondering when I should choose RabbitMQ instead of others like ZeroMQ or Kafka

**Comment by mrinc** [comment]
Lets start off with the one awesome part: we're not limited to rabbit.  
The system is designed to use a multitude of messaging brokers - incl kafka.  
The events plugin just needs to be written and then it can be used instead of rabbit.  

The main reason we chose rabbit though was simplicity, it did what we needed, and I had already used it in the past. 
Whereas kafka/zeroMQ, I'd have to play with and understand.  

The biggest thing comes down to the way it distributes the events.  
Example, for emit events - you only want a single endpoint to receive the event - it must not be received by another service (since the platform is designed to scale).  
Same for emitAndReturn - single service.  
Rabbit checked all the boxes, so we used it.
If we felt it didn't perform at a higher scale, we can switch over to something else with a few flicks :)  

If you have knowledge/experience with zero/kafka, you can just write the events plugin for it (we've done the core, so I can just push the service up and you can put a PR in for the actual code).  
And then you can use it.  

You can also write your own events plugin and publish it on github - just haven't finished the docs for it.  
But basically, BSB project, sec.config.json in the plugin definition.  
`bsb-plugin`, `bsb-node` - for github topics.  

We've got built in tests that are usable from the core bsb lib - to make sure your code works as intended.  

Hopefully that answers your questions :)

**Comment by mrinc** [comment]
- pushed up from rabbitMQ base - [https://github.com/BetterCorp/service-base-events-kafka](https://github.com/BetterCorp/service-base-events-kafka)  
 - Of course just needs to be written for Kafka, but the base is there.
